import json
import time
from typing import Dict, Any, Set
from pydantic import BaseModel, Field
from web3 import Web3
from eth_account import Account
from eth_account.messages import encode_typed_data
from .registry import parse_agent_did, build_agent_did


class AgentRequestEnvelope(BaseModel):
    """
    Cryptographic envelope that wraps agent-to-agent message payloads.
    Secures request integrity and identity.
    """
    sender_did: str = Field(..., description="DID of the agent sending the request.")
    recipient_did: str = Field(..., description="DID of the target agent.")
    payload: Dict[str, Any] = Field(..., description="The raw request payload dictionary.")
    timestamp: int = Field(..., description="Unix epoch timestamp of when the request was signed.")
    nonce: int = Field(..., description="Anti-replay incrementing or random nonce.")
    signature: str = Field(..., description="EIP-712 signature generated by the sender agent.")


def build_request_eip712_struct(
    sender_address: str,
    recipient_address: str,
    payload_hash: bytes,
    timestamp: int,
    nonce: int,
    chain_id: int = 31337
) -> Dict[str, Any]:
    """Builds the EIP-712 structured data dictionary for signing."""
    w3 = Web3()
    return {
        "types": {
            "EIP712Domain": [
                {"name": "name", "type": "string"},
                {"name": "version", "type": "string"},
                {"name": "chainId", "type": "uint256"},
                {"name": "verifyingContract", "type": "address"}
            ],
            "AgentRequest": [
                {"name": "sender", "type": "address"},
                {"name": "recipient", "type": "address"},
                {"name": "payloadHash", "type": "bytes32"},
                {"name": "timestamp", "type": "uint256"},
                {"name": "nonce", "type": "uint256"}
            ]
        },
        "primaryType": "AgentRequest",
        "domain": {
            "name": "AgentMailroomRequest",
            "version": "1",
            "chainId": chain_id,
            "verifyingContract": "0x0000000000000000000000000000000000000100"
        },
        "message": {
            "sender": w3.to_checksum_address(sender_address),
            "recipient": w3.to_checksum_address(recipient_address),
            "payloadHash": payload_hash,
            "timestamp": timestamp,
            "nonce": nonce
        }
    }


class AgentAuth:
    """Handles generation and cryptographic verification of Agent-to-Agent requests."""

    def __init__(self, max_timestamp_drift_sec: int = 300):
        self.max_timestamp_drift_sec = max_timestamp_drift_sec
        # In-memory tracking of processed (sender_address, nonce) tuples to prevent replay
        self.used_nonces: Set[tuple[str, int]] = set()

    def sign_request(
        self,
        sender_private_key: str,
        recipient_did: str,
        payload: Dict[str, Any],
        nonce: int,
        chain_id: int = 31337
    ) -> AgentRequestEnvelope:
        """
        Signs a payload and returns the request envelope ready to send.
        """
        w3 = Web3()
        # Derive sender address from key
        sender_account = Account.from_key(sender_private_key)
        sender_address = sender_account.address
        sender_did = build_agent_did(sender_address)
        
        recipient_address = parse_agent_did(recipient_did)
        timestamp = int(time.time())

        # Hash payload
        payload_json = json.dumps(payload, sort_keys=True)
        payload_hash = w3.keccak(text=payload_json)

        # Build structure
        eip712_data = build_request_eip712_struct(
            sender_address=sender_address,
            recipient_address=recipient_address,
            payload_hash=payload_hash,
            timestamp=timestamp,
            nonce=nonce,
            chain_id=chain_id
        )

        # Sign typed data
        signable_msg = encode_typed_data(full_message=eip712_data)
        signed_msg = Account.sign_message(signable_msg, private_key=sender_private_key)
        signature = signed_msg.signature.hex()

        return AgentRequestEnvelope(
            sender_did=sender_did,
            recipient_did=recipient_did,
            payload=payload,
            timestamp=timestamp,
            nonce=nonce,
            signature=signature
        )

    def verify_request(
        self,
        envelope: AgentRequestEnvelope,
        expected_recipient_did: str,
        chain_id: int = 31337
    ) -> str:
        """
        Verifies request authenticity, recipient target, freshness, and nonces.

        Returns:
            str: The verified sender's checksummed Ethereum address.

        Raises:
            ValueError: If validation checks or signature recoveries fail.
        """
        w3 = Web3()
        current_time = int(time.time())

        # 1. Verify target recipient match
        if envelope.recipient_did.lower() != expected_recipient_did.lower():
            raise ValueError(
                f"Recipient DID mismatch. Expected {expected_recipient_did}, "
                f"got {envelope.recipient_did}"
            )

        # 2. Verify timestamp drift
        drift = abs(current_time - envelope.timestamp)
        if drift > self.max_timestamp_drift_sec:
            raise ValueError(
                f"Request timestamp drift too high ({drift}s). "
                f"Request expired or clock is out of sync."
            )

        # 3. Resolve addresses
        sender_address = parse_agent_did(envelope.sender_did)
        recipient_address = parse_agent_did(envelope.recipient_did)

        # 4. Check replay protection (nonce reuse)
        nonce_key = (sender_address, envelope.nonce)
        if nonce_key in self.used_nonces:
            raise ValueError(f"Replay attack detected: Nonce {envelope.nonce} already used by {sender_address}.")

        # 5. Verify Cryptographic Signature
        payload_json = json.dumps(envelope.payload, sort_keys=True)
        payload_hash = w3.keccak(text=payload_json)

        eip712_data = build_request_eip712_struct(
            sender_address=sender_address,
            recipient_address=recipient_address,
            payload_hash=payload_hash,
            timestamp=envelope.timestamp,
            nonce=envelope.nonce,
            chain_id=chain_id
        )

        signable_msg = encode_typed_data(full_message=eip712_data)
        try:
            recovered_address = Account.recover_message(signable_msg, signature=envelope.signature)
        except Exception as e:
            raise ValueError(f"Failed to recover signer: {str(e)}") from e

        if w3.to_checksum_address(recovered_address) != sender_address:
            raise ValueError(
                f"Signature verification failed. Recovered signer {recovered_address} "
                f"does not match declared sender {sender_address}."
            )

        # Mark nonce as consumed
        self.used_nonces.add(nonce_key)

        return sender_address
