// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title AgentRegistry
 * @dev On-chain Decentralized Identifier (DID) Registry for AI Agents.
 *      Maps agent addresses (their public keys) to metadata detailing their
 *      controllers, endpoints, capability models, and service pricing.
 */
contract AgentRegistry {
    
    struct AgentProfile {
        address owner;
        string endpoint;
        string modelCapabilities;
        uint256 ratePerTaskWei;
        bool active;
    }

    // Maps agent address (EIP-55 checksummed) to its Profile
    mapping(address => AgentProfile) private _registry;

    // Events
    event AgentRegistered(
        address indexed agent, 
        address indexed owner, 
        string endpoint, 
        uint256 ratePerTaskWei
    );
    event AgentProfileUpdated(
        address indexed agent, 
        string endpoint, 
        string modelCapabilities, 
        uint256 ratePerTaskWei
    );
    event AgentDeregistered(address indexed agent);

    modifier onlyAgentOwner(address agent) {
        require(_registry[agent].active, "Agent is not registered");
        require(_registry[agent].owner == msg.sender, "Caller is not the agent owner");
        _;
    }

    /**
     * @notice Registers a new agent profile under the caller's control.
     * @param agent Address of the agent key (e.g. session/signing key generated by the agent).
     * @param endpoint HTTP URL endpoint where the agent processes incoming messages.
     * @param modelCapabilities Comma-separated list of capabilities/models (e.g. "gpt-4o,llama-3").
     * @param ratePerTaskWei Payment rate required per task execution in Wei.
     */
    function registerAgent(
        address agent,
        string calldata endpoint,
        string calldata modelCapabilities,
        uint256 ratePerTaskWei
    ) external {
        require(agent != address(0), "Invalid agent address");
        require(!_registry[agent].active, "Agent already registered");
        
        _registry[agent] = AgentProfile({
            owner: msg.sender,
            endpoint: endpoint,
            modelCapabilities: modelCapabilities,
            ratePerTaskWei: ratePerTaskWei,
            active: true
        });

        emit AgentRegistered(agent, msg.sender, endpoint, ratePerTaskWei);
    }

    /**
     * @notice Updates an existing agent's profile details. Can only be called by the agent's owner.
     * @param agent Address of the registered agent.
     * @param endpoint New HTTP URL endpoint.
     * @param modelCapabilities New capabilities string.
     * @param ratePerTaskWei New rate per task in Wei.
     */
    function updateAgentProfile(
        address agent,
        string calldata endpoint,
        string calldata modelCapabilities,
        uint256 ratePerTaskWei
    ) external onlyAgentOwner(agent) {
        AgentProfile storage profile = _registry[agent];
        profile.endpoint = endpoint;
        profile.modelCapabilities = modelCapabilities;
        profile.ratePerTaskWei = ratePerTaskWei;

        emit AgentProfileUpdated(agent, endpoint, modelCapabilities, ratePerTaskWei);
    }

    /**
     * @notice Deregisters an agent profile, removing it from active status. Can only be called by owner.
     * @param agent Address of the registered agent.
     */
    function deregisterAgent(address agent) external onlyAgentOwner(agent) {
        _registry[agent].active = false;
        emit AgentDeregistered(agent);
    }

    /**
     * @notice Retrieves details of an agent by address.
     * @param agent Address of the agent.
     */
    function getAgent(address agent) 
        external 
        view 
        returns (
            address owner,
            string memory endpoint,
            string memory modelCapabilities,
            uint256 ratePerTaskWei,
            bool active
        ) 
    {
        AgentProfile memory profile = _registry[agent];
        return (
            profile.owner,
            profile.endpoint,
            profile.modelCapabilities,
            profile.ratePerTaskWei,
            profile.active
        );
    }
}
